Transform Library: include/bitreverse.hpp File Reference
bitreverse.hpp File Reference
Declares functions for bit-reversing vectors and 3D vectors (images).
#include <cstddef>
#include <cstdint>
#include "typedefs.hpp"
Functions
auto partial_bit_reverse (Typedefs::vec &signal, size_t n, uint8_t levels) -> void
Perform partial bit-reversal on a signal vector.
template<typename T >
auto bit_reverse_copy (T &v) -> void
Perform bit-reversal on a vector by creating a new bit-reversed copy.
auto next_multiple_of_levels (size_t n, size_t m) -> size_t
Find the next multiple of a given value that is greater than or equal to a given number.
auto bit_reverse_image (Typedefs::vec3D &image, uint8_t user_levels) -> void
Perform bit-reversal on a 3D vector (image).
auto reverse_bit_reverse_image (Typedefs::vec3D &bit_reversed_image, uint8_t levels) -> void
Reverse the bit-reversal operation on a 3D vector (image).
Detailed Description
Declares functions for bit-reversing vectors and 3D vectors (images).
Definition in file bitreverse.hpp.
Function Documentation
bit_reverse_copy()
template<typename T > auto bit_reverse_copy (T & v) -> void
Perform bit-reversal on a vector by creating a new bit-reversed copy.
Template Parameters
T The data type of the vector elements.
Parameters
v The input vector.
Definition at line 60 of file bitreverse.cpp.
References bit_reverse().
Referenced by DiscreteWaveletTransform::OutputSpace::compress(), and DiscreteWaveletTransform::OutputSpace::get_plottable_representation().
bit_reverse_image()
auto bit_reverse_image (Typedefs::vec3D & image, uint8_t user_levels) -> void
Perform bit-reversal on a 3D vector (image).
Parameters
image The input image as a 3D vector.
user_levels The number of levels for bit-reversal.
Definition at line 77 of file bitreverse.cpp.
References compression::c, and partial_bit_reverse().
Referenced by DiscreteWaveletTransform2D::OutputSpace::get_plottable_representation().
next_multiple_of_levels()
auto next_multiple_of_levels (size_t n, size_t m) -> size_t
Find the next multiple of a given value that is greater than or equal to a given number.
Parameters
n The number for which the next multiple needs to be found.
m The value with respect to which the multiple needs to be found.
Returns
The next multiple of m that is greater than or equal to n.
Definition at line 70 of file bitreverse.cpp.
References plot_scaling_tests_results::m, and plot_scaling_tests_results::n.
Referenced by DiscreteWaveletTransform2D::get_input_space().
partial_bit_reverse()
auto partial_bit_reverse (Typedefs::vec & signal, size_t n, uint8_t levels) -> void
Perform partial bit-reversal on a signal vector.
Parameters
signal The signal vector to be bit-reversed.
n The size of the signal vector.
levels The number of levels for bit-reversal.
Definition at line 23 of file bitreverse.cpp.
References plot_scaling_tests_results::b, bit_reversed_index(), and plot_scaling_tests_results::n.
Referenced by bit_reverse_image().
reverse_bit_reverse_image()
auto reverse_bit_reverse_image (Typedefs::vec3D & bit_reversed_image, uint8_t levels) -> void
Reverse the bit-reversal operation on a 3D vector (image).
Parameters
bit_reversed_image The bit-reversed image as a 3D vector.
levels The number of levels used for bit-reversal.
Definition at line 104 of file bitreverse.cpp.
References compression::c.