Transform Library: src/bitreverse.cpp File Reference
bitreverse.cpp File Reference
#include <omp.h>
#include <algorithm>
#include <bitset>
#include <cmath>
#include <cstdint>
#include "bitreverse.hpp"
#include "typedefs.hpp"
Functions
auto bit_reversed_index (int index, uint8_t levels) -> int
auto partial_bit_reverse (vec &signal, size_t n, uint8_t levels) -> void
Perform partial bit-reversal on a signal vector.
auto bit_reverse (size_t i, size_t N) -> size_t
template<typename T >
auto bit_reverse_copy (T &v) -> void
Perform bit-reversal on a vector by creating a new bit-reversed copy.
auto next_multiple_of_levels (size_t n, size_t m) -> size_t
Find the next multiple of a given value that is greater than or equal to a given number.
auto bit_reverse_image (Typedefs::vec3D &image, uint8_t user_levels) -> void
Perform bit-reversal on a 3D vector (image).
auto reverse_bit_reverse_image (vec3D &bit_reversed_image, uint8_t levels) -> void
Reverse the bit-reversal operation on a 3D vector (image).
template void bit_reverse_copy< vec > (vec &v)
template void bit_reverse_copy< vcpx > (vcpx &v)
Function Documentation
bit_reverse()
auto bit_reverse (size_t i, size_t N) -> size_t
Definition at line 47 of file bitreverse.cpp.
References plot_scaling_tests_results::b, and plot_scaling_tests_results::m.
Referenced by bit_reverse_copy().
bit_reverse_copy()
template<typename T > auto bit_reverse_copy (T & v) -> void
Perform bit-reversal on a vector by creating a new bit-reversed copy.
Template Parameters
T The data type of the vector elements.
Parameters
v The input vector.
Definition at line 60 of file bitreverse.cpp.
References bit_reverse().
Referenced by DiscreteWaveletTransform::OutputSpace::compress(), and DiscreteWaveletTransform::OutputSpace::get_plottable_representation().
bit_reverse_copy< vcpx >()
template void bit_reverse_copy< vcpx > (vcpx & v)
bit_reverse_copy< vec >()
template void bit_reverse_copy< vec > (vec & v)
bit_reverse_image()
auto bit_reverse_image (Typedefs::vec3D & image, uint8_t user_levels) -> void
Perform bit-reversal on a 3D vector (image).
Parameters
image The input image as a 3D vector.
user_levels The number of levels for bit-reversal.
Definition at line 77 of file bitreverse.cpp.
References compression::c, and partial_bit_reverse().
Referenced by DiscreteWaveletTransform2D::OutputSpace::get_plottable_representation().
bit_reversed_index()
auto bit_reversed_index (int index, uint8_t levels) -> int
Definition at line 12 of file bitreverse.cpp.
Referenced by partial_bit_reverse().
next_multiple_of_levels()
auto next_multiple_of_levels (size_t n, size_t m) -> size_t
Find the next multiple of a given value that is greater than or equal to a given number.
Parameters
n The number for which the next multiple needs to be found.
m The value with respect to which the multiple needs to be found.
Returns
The next multiple of m that is greater than or equal to n.
Definition at line 70 of file bitreverse.cpp.
References plot_scaling_tests_results::m, and plot_scaling_tests_results::n.
Referenced by DiscreteWaveletTransform2D::get_input_space().
partial_bit_reverse()
auto partial_bit_reverse (Typedefs::vec & signal, size_t n, uint8_t levels) -> void
Perform partial bit-reversal on a signal vector.
Parameters
signal The signal vector to be bit-reversed.
n The size of the signal vector.
levels The number of levels for bit-reversal.
Definition at line 23 of file bitreverse.cpp.
References plot_scaling_tests_results::b, bit_reversed_index(), and plot_scaling_tests_results::n.
Referenced by bit_reverse_image().
reverse_bit_reverse_image()
auto reverse_bit_reverse_image (Typedefs::vec3D & bit_reversed_image, uint8_t levels) -> void
Reverse the bit-reversal operation on a 3D vector (image).
Parameters
bit_reversed_image The bit-reversed image as a 3D vector.
levels The number of levels used for bit-reversal.
Definition at line 104 of file bitreverse.cpp.
References compression::c.