Transform Library: Signal Class Reference
Signal Class Reference
Class for generating and transforming signals using Fourier Transform.
#include <Signal.hpp>
Public Member Functions
Signal (Typedefs::vec freqs, Typedefs::vec amps, size_t N, std::unique_ptr< Transform< Typedefs::vec >> tr, bool padding=true)
Constructor for the Signal class.
auto denoise (const double flat_freq) -> void
Denoises the signal by filtering out frequencies above the specified flat frequency.
auto get_signal () const -> const Typedefs::vec &
Gets the generated signal.
auto get_x () const -> const Typedefs::vec &
Gets the sample points of the signal.
auto get_freqs () const -> const Typedefs::vec
Gets the frequencies of the signal components.
Detailed Description
Class for generating and transforming signals using Fourier Transform.
Definition at line 17 of file Signal.hpp.
Constructor & Destructor Documentation
Signal()
Signal::Signal (Typedefs::vec freqs, Typedefs::vec amps, size_t N, std::unique_ptr< Transform< Typedefs::vec >> tr, bool padding = true)
Constructor for the Signal class.
Parameters
freqs Vector of frequencies for the signal components.
amps Vector of amplitudes for the signal components.
N Number of samples.
tr Unique pointer to a Transform object for signal processing.
padding Boolean indicating if padding should be applied (default is true).
Definition at line 10 of file Signal.cpp.
References next_power_of_2().
Member Function Documentation
denoise()
auto Signal::denoise (const double flat_freq) -> void
Denoises the signal by filtering out frequencies above the specified flat frequency.
Parameters
flat_freq Frequency threshold for filtering.
Definition at line 42 of file Signal.cpp.
References compression::tr.
Referenced by main().
get_freqs()
auto Signal::get_freqs () const -> const Typedefs::vec
Gets the frequencies of the signal components.
Returns
Vector of frequencies.
Definition at line 58 of file Signal.cpp.
Referenced by main().
get_signal()
auto Signal::get_signal () const -> const Typedefs::vec&
Gets the generated signal.
Returns
Constant reference to the generated signal vector.
Definition at line 48 of file Signal.cpp.
Referenced by main().
get_x()
auto Signal::get_x () const -> const Typedefs::vec&
Gets the sample points of the signal.
Returns
Constant reference to the sample points vector.
Definition at line 53 of file Signal.cpp.
Referenced by main().
The documentation for this class was generated from the following files:
apps/Signal/include/Signal.hpp
apps/Signal/src/Signal.cpp