Transform Library: DiscreteWaveletTransform Class Reference
DiscreteWaveletTransform Class Reference
Represents a discrete wavelet transform operation.
#include <DiscreteWaveletTransform.hpp>
Classes
class InputSpace
Represents the input space for the discrete wavelet transform.
class OutputSpace
Represents the output space for the discrete wavelet transform.
Public Member Functions
template<std::size_t N>
DiscreteWaveletTransform (const TRANSFORM_MATRICES::TransformMatrix< Typedefs::DType, N > &scaling_matrix, uint8_t user_levels=0, int n_cores=-1)
Constructor for the DiscreteWaveletTransform class.
auto get_input_space (const Typedefs::vec &v) const -> std::unique_ptr< Transform::InputSpace > override
Get the input space for the discrete wavelet transform.
auto get_output_space () const -> std::unique_ptr< Transform::OutputSpace > override
Get the output space for the discrete wavelet transform.
auto set_n_cores (const int n_cores) -> void
Set the number of cores to be used for parallel computation.
auto operator() (Typedefs::vec &signal, const bool is_inverse) const -> void
Perform the discrete wavelet transform operation on a signal vector.
auto operator() (Transform::InputSpace &in, Transform::OutputSpace &out, const bool inverse) const -> void override
Perform the discrete wavelet transform operation.
Public Member Functions inherited from Transform< Typedefs::vec >
virtual ~Transform ()=default
virtual auto operator() (InputSpace &input, OutputSpace &output, const bool flag) const -> void=0
Perform the transformation operation.
Detailed Description
Represents a discrete wavelet transform operation.
Template Parameters
Typedefs::vec The vector type used for input and output data.
Definition at line 19 of file DiscreteWaveletTransform.hpp.
Constructor & Destructor Documentation
DiscreteWaveletTransform()
template<std::size_t N> DiscreteWaveletTransform::DiscreteWaveletTransform (const TRANSFORM_MATRICES::TransformMatrix< Typedefs::DType, N > & scaling_matrix, uint8_t user_levels = 0, int n_cores = -1) inline
Constructor for the DiscreteWaveletTransform class.
Template Parameters
N The size of the transform matrix.
Parameters
scaling_matrix The TransformMatrix object containing the transform matrices.
user_levels The number of levels to be used in the transform (default: 0).
n_cores The number of cores to be used for parallel computation (default: -1, meaning automatic detection).
Definition at line 79 of file DiscreteWaveletTransform.hpp.
Member Function Documentation
get_input_space()
auto DiscreteWaveletTransform::get_input_space (const Typedefs::vec & v) const -> std::unique_ptr<Transform::InputSpace> override virtual
Get the input space for the discrete wavelet transform.
Parameters
v The input data.
Returns
A unique pointer to the InputSpace object.
Implements Transform< Typedefs::vec >.
Definition at line 31 of file DiscreteWaveletTransform.cpp.
get_output_space()
auto DiscreteWaveletTransform::get_output_space () const -> std::unique_ptr<Transform::OutputSpace> override virtual
Get the output space for the discrete wavelet transform.
Returns
A unique pointer to the OutputSpace object.
Implements Transform< Typedefs::vec >.
Definition at line 36 of file DiscreteWaveletTransform.cpp.
operator()() [1/2]
auto DiscreteWaveletTransform::operator() (Transform::InputSpace & in, Transform::OutputSpace & out, const bool inverse) const -> void override
Perform the discrete wavelet transform operation.
Parameters
in The input space for the transformation.
out The output space for the transformation.
inverse A flag indicating whether to perform the inverse transform.
Definition at line 82 of file DiscreteWaveletTransform.cpp.
References plot_scaling_tests_results::data, and operator()().
operator()() [2/2]
auto DiscreteWaveletTransform::operator() (Typedefs::vec & signal, const bool is_inverse) const -> void
Perform the discrete wavelet transform operation on a signal vector.
Parameters
signal The input signal vector.
is_inverse A flag indicating whether to perform the inverse transform.
Referenced by operator()().
set_n_cores()
auto DiscreteWaveletTransform::set_n_cores (const int n_cores) -> void inline
Set the number of cores to be used for parallel computation.
Parameters
n_cores The number of cores.
Definition at line 101 of file DiscreteWaveletTransform.hpp.
Referenced by dwt_tests().
The documentation for this class was generated from the following files:
include/DiscreteWaveletTransform.hpp
src/DiscreteWaveletTransform.cpp