Transform Library: Image Class Reference
Image Class Reference
The Image class represents an image and provides methods for transformation, compression, and retrieval.
#include <Image.hpp>
Public Member Functions
Image (const cv::Mat &img, std::unique_ptr< Transform< cv::Mat >> tr)
Constructs an Image object.
auto transform () -> void
Performs the transformation on the image.
auto compress (const double percentile, const std::string &method) -> void
Compresses the image using the specified method and percentile.
auto get_image () const -> const cv::Mat
Retrieves the image as an OpenCV matrix.
auto get_tr_coeff () const -> const cv::Mat
Retrieves the transformation coefficients.
Detailed Description
The Image class represents an image and provides methods for transformation, compression, and retrieval.
Definition at line 17 of file Image.hpp.
Constructor & Destructor Documentation
Image()
Image::Image (const cv::Mat & img, std::unique_ptr< Transform< cv::Mat >> tr)
Constructs an Image object.
Parameters
img The OpenCV matrix representing the image.
tr The unique pointer to the transformation object.
Definition at line 11 of file Image.cpp.
Member Function Documentation
compress()
auto Image::compress (const double percentile, const std::string & method) -> void
Compresses the image using the specified method and percentile.
Parameters
percentile The percentile value for compression.
method The compression method to be used.
Definition at line 31 of file Image.cpp.
Referenced by main().
get_image()
auto Image::get_image () const -> const cv::Mat
Retrieves the image as an OpenCV matrix.
Returns
The OpenCV matrix representing the image.
Definition at line 41 of file Image.cpp.
Referenced by main().
get_tr_coeff()
auto Image::get_tr_coeff () const -> const cv::Mat
Retrieves the transformation coefficients.
Returns
The OpenCV matrix containing the transformation coefficients.
Definition at line 45 of file Image.cpp.
Referenced by main().
transform()
auto Image::transform () -> void
Performs the transformation on the image.
Definition at line 37 of file Image.cpp.
References compression::tr.
Referenced by main().
The documentation for this class was generated from the following files:
apps/Image/include/Image.hpp
apps/Image/src/Image.cpp