Transform Library: matplotlibcpp::detail Namespace Reference
matplotlibcpp::detail Namespace Reference
Classes
struct _interpreter
struct select_npy_type
struct select_npy_type< double >
struct select_npy_type< float >
struct select_npy_type< bool >
struct select_npy_type< int8_t >
struct select_npy_type< int16_t >
struct select_npy_type< int32_t >
struct select_npy_type< int64_t >
struct select_npy_type< uint8_t >
struct select_npy_type< uint16_t >
struct select_npy_type< uint32_t >
struct select_npy_type< uint64_t >
struct is_callable_impl
struct is_callable_impl< false, T >
struct is_callable_impl< true, T >
struct is_callable
struct plot_impl
struct plot_impl< std::false_type >
struct plot_impl< std::true_type >
Typedefs
template<typename T >
using is_function = typename std::is_function< std::remove_pointer< std::remove_reference< T > >>::type
Functions
template<typename Numeric >
PyObject * get_array (const std::vector< Numeric > &v)
template<typename Numeric >
PyObject * get_2darray (const std::vector<::std::vector< Numeric >> &v)
PyObject * get_array (const std::vector< std::string > &strings)
template<typename Numeric >
PyObject * get_listlist (const std::vector< std::vector< Numeric >> &ll)
void imshow (void *ptr, const NPY_TYPES type, const int rows, const int columns, const int colors, const std::map< std::string, std::string > &keywords, PyObject **out)
Typedef Documentation
is_function
template<typename T > using matplotlibcpp::detail::is_function = typedef typename std::is_function<std::remove_pointer<std::remove_reference<T> >>::type
Definition at line 2758 of file matplotlibcpp.h.
Function Documentation
get_2darray()
template<typename Numeric > PyObject* matplotlibcpp::detail::get_2darray (const std::vector<::std::vector< Numeric >> & v)
Definition at line 379 of file matplotlibcpp.h.
Referenced by matplotlibcpp::plot_surface().
get_array() [1/2]
template<typename Numeric > PyObject* matplotlibcpp::detail::get_array (const std::vector< Numeric > & v)
Definition at line 359 of file matplotlibcpp.h.
Referenced by matplotlibcpp::fill(), matplotlibcpp::fill_between(), get_listlist(), matplotlibcpp::hist(), matplotlibcpp::loglog(), matplotlibcpp::named_hist(), matplotlibcpp::named_loglog(), matplotlibcpp::named_plot(), matplotlibcpp::named_semilogx(), matplotlibcpp::named_semilogy(), matplotlibcpp::Plot::Plot(), matplotlibcpp::plot(), matplotlibcpp::plot3(), matplotlibcpp::semilogx(), matplotlibcpp::semilogy(), matplotlibcpp::stem(), and matplotlibcpp::Plot::update().
get_array() [2/2]
PyObject* matplotlibcpp::detail::get_array (const std::vector< std::string > & strings) inline
Definition at line 416 of file matplotlibcpp.h.
get_listlist()
template<typename Numeric > PyObject* matplotlibcpp::detail::get_listlist (const std::vector< std::vector< Numeric >> & ll)
Definition at line 427 of file matplotlibcpp.h.
References get_array().
imshow()
void matplotlibcpp::detail::imshow (void * ptr, const NPY_TYPES type, const int rows, const int columns, const int colors, const std::map< std::string, std::string > & keywords, PyObject ** out) inline
Definition at line 918 of file matplotlibcpp.h.
References matplotlibcpp::detail::_interpreter::get().
Referenced by main(), and plot_image().