Transform Library: tr::test_suite Namespace Reference
tr::test_suite Namespace Reference
Functions
auto time_ev (const Typedefs::vcpx &x, const std::unique_ptr< tr::FourierTransform > &fft) -> long unsigned int
Time the execution of a Fourier transform on a complex signal.
auto time_ev_dwt (const Typedefs::vec &x, const tr::DiscreteWaveletTransform &dwt) -> long unsigned int
Time the execution of a discrete wavelet transform on a signal vector.
Function Documentation
time_ev()
auto tr::test_suite::time_ev (const Typedefs::vcpx & x, const std::unique_ptr< tr::FourierTransform > & fft) -> long unsigned int
Time the execution of a Fourier transform on a complex signal.
Parameters
x The input complex signal.
fft The Fourier transform object.
Returns
The execution time in microseconds.
Referenced by strong_scaling_evaluation(), time_evaluation(), and weak_scaling_evaluation().
time_ev_dwt()
auto tr::test_suite::time_ev_dwt (const Typedefs::vec & x, const tr::DiscreteWaveletTransform & dwt) -> long unsigned int
Time the execution of a discrete wavelet transform on a signal vector.
Parameters
x The input signal vector.
dwt The discrete wavelet transform object.
Returns
The execution time in microseconds.
Definition at line 20 of file time_evaluator.cpp.
Referenced by dwt_tests().