Transform Library: apps/Signal/src/main.cpp File Reference
main.cpp File Reference
#include <iostream>
#include <vector>
#include <cmath>
#include <complex>
#include <typedefs.hpp>
#include <matplotlibcpp.h>
#include <Signal.hpp>
#include <FourierTransform.hpp>
#include <DiscreteFourierTransform.hpp>
#include <RecursiveFastFourierTransform.hpp>
#include <IterativeFastFourierTransform.hpp>
#include <DiscreteWaveletTransform.hpp>
Functions
auto plot_stuff (vec &x, vec &y, vec &y2, vec &freq, vec &freq_filtered, const int N, const bool truncate=false) -> void
auto main () -> int
Function Documentation
main()
auto main () -> int
Definition at line 53 of file main.cpp.
References TRANSFORM_MATRICES::DAUBECHIES_D40, Signal::denoise(), Signal::get_freqs(), Signal::get_signal(), Signal::get_x(), plot_stuff(), plot_scaling_tests_results::time, and compression::tr.
plot_stuff()
auto plot_stuff (vec & x, vec & y, vec & y2, vec & freq, vec & freq_filtered, const int N, const bool truncate = false) -> void
Definition at line 21 of file main.cpp.
References plot_scaling_tests_results::color, matplotlibcpp::figure_size(), matplotlibcpp::plot(), matplotlibcpp::save(), matplotlibcpp::show(), matplotlibcpp::subplot(), and matplotlibcpp::title().
Referenced by main().