Transform Library: matplotlibcpp::detail::_interpreter Struct Reference
matplotlibcpp::detail::_interpreter Struct Reference
#include <matplotlibcpp.h>
Public Member Functions
PyObject * safe_import (PyObject *module, std::string fname)
Static Public Member Functions
static _interpreter & get ()
static _interpreter & kill ()
static _interpreter & interkeeper (bool should_kill)
Public Attributes
PyObject * s_python_function_arrow
PyObject * s_python_function_show
PyObject * s_python_function_close
PyObject * s_python_function_draw
PyObject * s_python_function_pause
PyObject * s_python_function_save
PyObject * s_python_function_figure
PyObject * s_python_function_fignum_exists
PyObject * s_python_function_plot
PyObject * s_python_function_quiver
PyObject * s_python_function_contour
PyObject * s_python_function_semilogx
PyObject * s_python_function_semilogy
PyObject * s_python_function_loglog
PyObject * s_python_function_fill
PyObject * s_python_function_fill_between
PyObject * s_python_function_hist
PyObject * s_python_function_imshow
PyObject * s_python_function_scatter
PyObject * s_python_function_boxplot
PyObject * s_python_function_subplot
PyObject * s_python_function_subplot2grid
PyObject * s_python_function_legend
PyObject * s_python_function_xlim
PyObject * s_python_function_ion
PyObject * s_python_function_ginput
PyObject * s_python_function_ylim
PyObject * s_python_function_title
PyObject * s_python_function_axis
PyObject * s_python_function_axhline
PyObject * s_python_function_axvline
PyObject * s_python_function_axvspan
PyObject * s_python_function_xlabel
PyObject * s_python_function_ylabel
PyObject * s_python_function_gca
PyObject * s_python_function_xticks
PyObject * s_python_function_yticks
PyObject * s_python_function_margins
PyObject * s_python_function_tick_params
PyObject * s_python_function_grid
PyObject * s_python_function_cla
PyObject * s_python_function_clf
PyObject * s_python_function_errorbar
PyObject * s_python_function_annotate
PyObject * s_python_function_tight_layout
PyObject * s_python_colormap
PyObject * s_python_empty_tuple
PyObject * s_python_function_stem
PyObject * s_python_function_xkcd
PyObject * s_python_function_text
PyObject * s_python_function_suptitle
PyObject * s_python_function_bar
PyObject * s_python_function_barh
PyObject * s_python_function_colorbar
PyObject * s_python_function_subplots_adjust
PyObject * s_python_function_rcparams
PyObject * s_python_function_spy
Detailed Description
Definition at line 48 of file matplotlibcpp.h.
Member Function Documentation
get()
static _interpreter& matplotlibcpp::detail::_interpreter::get () inline static
Definition at line 119 of file matplotlibcpp.h.
References interkeeper().
Referenced by matplotlibcpp::annotate(), matplotlibcpp::arrow(), matplotlibcpp::axhline(), matplotlibcpp::axis(), matplotlibcpp::axvline(), matplotlibcpp::axvspan(), matplotlibcpp::cla(), matplotlibcpp::clf(), matplotlibcpp::close(), matplotlibcpp::draw(), matplotlibcpp::fignum_exists(), matplotlibcpp::figure(), matplotlibcpp::figure_size(), matplotlibcpp::fill(), matplotlibcpp::fill_between(), matplotlibcpp::grid(), matplotlibcpp::hist(), matplotlibcpp::detail::imshow(), matplotlibcpp::ion(), matplotlibcpp::legend(), matplotlibcpp::loglog(), matplotlibcpp::margins(), matplotlibcpp::named_hist(), matplotlibcpp::named_loglog(), matplotlibcpp::named_plot(), matplotlibcpp::named_semilogx(), matplotlibcpp::named_semilogy(), matplotlibcpp::detail::plot_impl< std::false_type >::operator()(), matplotlibcpp::pause(), matplotlibcpp::Plot::Plot(), matplotlibcpp::plot(), matplotlibcpp::plot3(), matplotlibcpp::plot_surface(), matplotlibcpp::save(), matplotlibcpp::semilogx(), matplotlibcpp::semilogy(), matplotlibcpp::set_aspect(), matplotlibcpp::set_aspect_equal(), matplotlibcpp::show(), matplotlibcpp::stem(), matplotlibcpp::subplot(), matplotlibcpp::subplot2grid(), matplotlibcpp::text(), matplotlibcpp::tick_params(), matplotlibcpp::tight_layout(), matplotlibcpp::xkcd(), matplotlibcpp::xlim(), and matplotlibcpp::ylim().
interkeeper()
static _interpreter& matplotlibcpp::detail::_interpreter::interkeeper (bool should_kill) inline static
Definition at line 128 of file matplotlibcpp.h.
Referenced by get(), and kill().
kill()
static _interpreter& matplotlibcpp::detail::_interpreter::kill () inline static
Definition at line 123 of file matplotlibcpp.h.
References interkeeper().
safe_import()
PyObject* matplotlibcpp::detail::_interpreter::safe_import (PyObject * module, std::string fname) inline
Definition at line 135 of file matplotlibcpp.h.
Member Data Documentation
s_python_colormap
PyObject* matplotlibcpp::detail::_interpreter::s_python_colormap
Definition at line 94 of file matplotlibcpp.h.
s_python_empty_tuple
PyObject* matplotlibcpp::detail::_interpreter::s_python_empty_tuple
Definition at line 95 of file matplotlibcpp.h.
s_python_function_annotate
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_annotate
Definition at line 92 of file matplotlibcpp.h.
s_python_function_arrow
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_arrow
Definition at line 49 of file matplotlibcpp.h.
s_python_function_axhline
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_axhline
Definition at line 78 of file matplotlibcpp.h.
s_python_function_axis
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_axis
Definition at line 77 of file matplotlibcpp.h.
s_python_function_axvline
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_axvline
Definition at line 79 of file matplotlibcpp.h.
s_python_function_axvspan
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_axvspan
Definition at line 80 of file matplotlibcpp.h.
s_python_function_bar
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_bar
Definition at line 100 of file matplotlibcpp.h.
s_python_function_barh
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_barh
Definition at line 101 of file matplotlibcpp.h.
s_python_function_boxplot
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_boxplot
Definition at line 68 of file matplotlibcpp.h.
s_python_function_cla
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_cla
Definition at line 89 of file matplotlibcpp.h.
s_python_function_clf
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_clf
Definition at line 90 of file matplotlibcpp.h.
s_python_function_close
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_close
Definition at line 51 of file matplotlibcpp.h.
s_python_function_colorbar
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_colorbar
Definition at line 102 of file matplotlibcpp.h.
s_python_function_contour
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_contour
Definition at line 59 of file matplotlibcpp.h.
s_python_function_draw
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_draw
Definition at line 52 of file matplotlibcpp.h.
s_python_function_errorbar
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_errorbar
Definition at line 91 of file matplotlibcpp.h.
s_python_function_fignum_exists
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_fignum_exists
Definition at line 56 of file matplotlibcpp.h.
s_python_function_figure
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_figure
Definition at line 55 of file matplotlibcpp.h.
s_python_function_fill
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_fill
Definition at line 63 of file matplotlibcpp.h.
s_python_function_fill_between
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_fill_between
Definition at line 64 of file matplotlibcpp.h.
s_python_function_gca
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_gca
Definition at line 83 of file matplotlibcpp.h.
s_python_function_ginput
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_ginput
Definition at line 74 of file matplotlibcpp.h.
s_python_function_grid
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_grid
Definition at line 88 of file matplotlibcpp.h.
s_python_function_hist
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_hist
Definition at line 65 of file matplotlibcpp.h.
s_python_function_imshow
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_imshow
Definition at line 66 of file matplotlibcpp.h.
s_python_function_ion
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_ion
Definition at line 73 of file matplotlibcpp.h.
s_python_function_legend
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_legend
Definition at line 71 of file matplotlibcpp.h.
s_python_function_loglog
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_loglog
Definition at line 62 of file matplotlibcpp.h.
s_python_function_margins
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_margins
Definition at line 86 of file matplotlibcpp.h.
s_python_function_pause
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_pause
Definition at line 53 of file matplotlibcpp.h.
s_python_function_plot
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_plot
Definition at line 57 of file matplotlibcpp.h.
s_python_function_quiver
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_quiver
Definition at line 58 of file matplotlibcpp.h.
s_python_function_rcparams
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_rcparams
Definition at line 104 of file matplotlibcpp.h.
s_python_function_save
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_save
Definition at line 54 of file matplotlibcpp.h.
s_python_function_scatter
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_scatter
Definition at line 67 of file matplotlibcpp.h.
s_python_function_semilogx
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_semilogx
Definition at line 60 of file matplotlibcpp.h.
s_python_function_semilogy
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_semilogy
Definition at line 61 of file matplotlibcpp.h.
s_python_function_show
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_show
Definition at line 50 of file matplotlibcpp.h.
s_python_function_spy
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_spy
Definition at line 105 of file matplotlibcpp.h.
s_python_function_stem
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_stem
Definition at line 96 of file matplotlibcpp.h.
s_python_function_subplot
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_subplot
Definition at line 69 of file matplotlibcpp.h.
s_python_function_subplot2grid
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_subplot2grid
Definition at line 70 of file matplotlibcpp.h.
s_python_function_subplots_adjust
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_subplots_adjust
Definition at line 103 of file matplotlibcpp.h.
s_python_function_suptitle
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_suptitle
Definition at line 99 of file matplotlibcpp.h.
s_python_function_text
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_text
Definition at line 98 of file matplotlibcpp.h.
s_python_function_tick_params
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_tick_params
Definition at line 87 of file matplotlibcpp.h.
s_python_function_tight_layout
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_tight_layout
Definition at line 93 of file matplotlibcpp.h.
s_python_function_title
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_title
Definition at line 76 of file matplotlibcpp.h.
s_python_function_xkcd
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_xkcd
Definition at line 97 of file matplotlibcpp.h.
s_python_function_xlabel
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_xlabel
Definition at line 81 of file matplotlibcpp.h.
s_python_function_xlim
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_xlim
Definition at line 72 of file matplotlibcpp.h.
s_python_function_xticks
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_xticks
Definition at line 84 of file matplotlibcpp.h.
s_python_function_ylabel
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_ylabel
Definition at line 82 of file matplotlibcpp.h.
s_python_function_ylim
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_ylim
Definition at line 75 of file matplotlibcpp.h.
s_python_function_yticks
PyObject* matplotlibcpp::detail::_interpreter::s_python_function_yticks
Definition at line 85 of file matplotlibcpp.h.
The documentation for this struct was generated from the following file:
apps/Signal/include/matplotlibcpp.h