Transform Library: test_src/test_dwt.hpp File Reference
test_dwt.hpp File Reference
#include <iostream>
#include <fstream>
#include <typedefs.hpp>
#include <DiscreteWaveletTransform.hpp>
#include <bitreverse.hpp>
#include <utils.hpp>
#include <time_evaluator.hpp>
Functions
auto dwt_tests (const string &output_folder) -> int
Function Documentation
dwt_tests()
auto dwt_tests (const string & output_folder) -> int
Definition at line 17 of file test_dwt.hpp.
References TRANSFORM_MATRICES::DAUBECHIES_D40, plot_scaling_tests_results::n, read_signal(), DiscreteWaveletTransform::set_n_cores(), plot_scaling_tests_results::time, and time_ev_dwt().
Referenced by main().