Transform Library: test_src/test_fft.hpp File Reference
test_fft.hpp File Reference
#include <iostream>
#include <fstream>
#include <typedefs.hpp>
#include <DiscreteFourierTransform.hpp>
#include <RecursiveFastFourierTransform.hpp>
#include <IterativeFastFourierTransform.hpp>
#include <bitreverse.hpp>
#include <utils.hpp>
#include <time_evaluator.hpp>
Functions
void time_evaluation (const vcpx &s)
void strong_scaling_evaluation (const vcpx &s, ofstream &output_file)
void weak_scaling_evaluation (const vcpx &s, ofstream &output_file)
auto fft_tests (const string &output_folder) -> int
Function Documentation
fft_tests()
auto fft_tests (const string & output_folder) -> int
Definition at line 67 of file test_fft.hpp.
References compression::c, read_signal(), strong_scaling_evaluation(), time_evaluation(), and weak_scaling_evaluation().
Referenced by main().
strong_scaling_evaluation()
void strong_scaling_evaluation (const vcpx & s, ofstream & output_file)
Definition at line 34 of file test_fft.hpp.
References plot_scaling_tests_results::time, and time_ev().
Referenced by fft_tests().
time_evaluation()
void time_evaluation (const vcpx & s)
Definition at line 19 of file test_fft.hpp.
References time_ev().
Referenced by fft_tests().
weak_scaling_evaluation()
void weak_scaling_evaluation (const vcpx & s, ofstream & output_file)
Definition at line 52 of file test_fft.hpp.
References plot_scaling_tests_results::n, and time_ev().
Referenced by fft_tests().