Transform Library: include/time_evaluator.hpp File Reference
time_evaluator.hpp File Reference
Declares functions for timing the execution of Fourier and wavelet transforms.
#include <chrono>
#include "FourierTransform.hpp"
#include "DiscreteWaveletTransform.hpp"
Functions
auto time_ev (const Typedefs::vcpx &x, const std::unique_ptr< FourierTransform > &fft) -> long unsigned int
Time the execution of a Fourier transform on a complex signal.
auto time_ev_dwt (const Typedefs::vec &x, const DiscreteWaveletTransform &dwt) -> long unsigned int
Time the execution of a discrete wavelet transform on a signal vector.
Detailed Description
Declares functions for timing the execution of Fourier and wavelet transforms.
Definition in file time_evaluator.hpp.
Function Documentation
time_ev()
auto time_ev (const Typedefs::vcpx & x, const std::unique_ptr< FourierTransform > & fft) -> long unsigned int
Time the execution of a Fourier transform on a complex signal.
Parameters
x The input complex signal.
fft The Fourier transform object.
Returns
The execution time in microseconds.
Referenced by strong_scaling_evaluation(), time_evaluation(), and weak_scaling_evaluation().
time_ev_dwt()
auto time_ev_dwt (const Typedefs::vec & x, const DiscreteWaveletTransform & dwt) -> long unsigned int
Time the execution of a discrete wavelet transform on a signal vector.
Parameters
x The input signal vector.
dwt The discrete wavelet transform object.
Returns
The execution time in microseconds.
Definition at line 18 of file time_evaluator.cpp.
Referenced by dwt_tests().