Transform Library: include/utils.hpp File Reference
utils.hpp File Reference
Declares utility functions for various operations.
#include <cstddef>
#include <cstdint>
#include "typedefs.hpp"
Functions
auto next_power_of_2 (const std::size_t n) -> std::size_t
Find the next power of 2 that is greater than or equal to the given number.
auto countSubdivisions (unsigned int i, unsigned int j, const unsigned int rows, const unsigned int cols, const unsigned int subdivisions) -> int
Count the number of subdivisions for a given row and column index.
auto read_signal (const std::string &signal_file, Typedefs::vec &real_signal) -> void
Read a signal from a file and store it in a vector.
Detailed Description
Declares utility functions for various operations.
Definition in file utils.hpp.
Function Documentation
countSubdivisions()
auto countSubdivisions (unsigned int i, unsigned int j, const unsigned int rows, const unsigned int cols, const unsigned int subdivisions) -> int
Count the number of subdivisions for a given row and column index.
Parameters
i The row index.
j The column index.
rows The total number of rows.
cols The total number of columns.
subdivisions The number of subdivisions.
Returns
The count of subdivisions for the given row and column index.
Definition at line 22 of file utils.cpp.
Referenced by DiscreteWaveletTransform2D::OutputSpace::normalize_coefficients().
next_power_of_2()
auto next_power_of_2 (const std::size_t n) -> std::size_t
Find the next power of 2 that is greater than or equal to the given number.
Parameters
n The input number.
Returns
The next power of 2 that is greater than or equal to n.
Referenced by generate_signal_to_file(), FourierTransform2D< FT >::get_input_space(), and Signal::Signal().
read_signal()
auto read_signal (const std::string & signal_file, Typedefs::vec & real_signal) -> void
Read a signal from a file and store it in a vector.
Parameters
signal_file The path to the signal file.
real_signal The vector to store the read signal.
Referenced by dwt_tests(), and fft_tests().